# Generated by Django 4.0.5 on 2022-07-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=100)),
                ('question_description', models.CharField(max_length=10000)),
                ('question_input_file', models.CharField(max_length=200)),
                ('question_output_file', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(default='background.gif', upload_to='documents/')),
                ('submission_status', models.CharField(max_length=50)),
                ('submission_language', models.CharField(max_length=50)),
                ('submission_time', models.FloatField(default=100.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.user')),
            ],
        ),
    ]
