# Generated by Django 4.0.5 on 2022-07-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.TextField(default='WA')),
                ('time_of_submit', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_input_file',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_output_file',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='testcase',
            name='curr_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.question'),
        ),
        migrations.AddField(
            model_name='solution',
            name='curr_problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oj.question'),
        ),
    ]
